name: Build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: install electron native dependencies
      run: npm run postinstall
    - name: build windows x64 binary
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run electron:build
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: install electron native dependencies
      run: npm run postinstall
    - name: build macos intel binary
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run electron:build
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: install electron native dependencies
      run: npm run postinstall
    - name: build linux appimage binary
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run electron:build
